### ISSUE TITLE
Not claimed

### ISSUE THREAD

**Issue by serialame** [shamblesides/turfwar#10]
IPs are not being claimed/not being added to users list!

**Comment by shamblesides** [comment]
The caching was overly conservative but should be fixed now, try again?

**Comment by serialame** [comment]
It still isnt doing it/takes a long time, i think you shouldn't use too much caching for a site like this. After claiming an IP it doesnt show that it has already been claimed aswell!

**Comment by shamblesides** [comment]
Just updated the user page to include the "last updated" time, for reference. And yeah it doesn't show a special "already claimed" message anymore, sorry! Other than that, it's working for me so I'm not sure what the issue is.

**Comment by serialame** [comment]
Oh that timer is good, thanks. Don't worry about the already claimed text, it was nice but not needed

Good work mate
